Do make sure that the build did not leave uncommitted changes behind
The strategy used by Git for Windows for years was that the Azure
Pipeline that built the packages and deployed them would then commit the
changes and push directly to the `main` branch.

However, we are changing that model out: We'll use branch deploys going
forward, where packages are built and deployed from PR branches, and
once that is successful, the PR is merged.

That means that all necessary changes, including the `pkgver`
modification, needs to be made up front, not by the same build that
deploys the packages.

Make sure of that.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -182,8 +182,18 @@ jobs:
           mkdir -p "$dir" &&
           cd "/usr/src/$REPO/$PACKAGE_TO_BUILD" &&
           MAKEFLAGS=-j6 PKGEXT='.pkg.tar.xz' makepkg-mingw -s --noconfirm &&
+          cp *.pkg.tar* "$dir/" &&
+
+          # Ensure that the Git worktree is still clean
           ls -la &&
-          cp *.pkg.tar* "$dir/"
+          if ! git update-index --ignore-submodules --refresh ||
+            ! git diff-files --ignore-submodules ||
+            ! git diff-index --cached --ignore-submodules HEAD
+          then
+            echo "::error::Uncommitted changes after build!" >&2
+            git diff
+            exit 1
+          fi
 
       - name: update check-run
         uses: actions/github-script@v6
