git-artifacts: get the `bundle-artifacts` first thing
We need this because we want to know what is the target commit as early
as possible so that we can mirror a Check Run to that target commit.

This commit is best viewed with `--color-moved`.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/.github/workflows/git-artifacts.yml b/.github/workflows/git-artifacts.yml
--- a/.github/workflows/git-artifacts.yml
+++ b/.github/workflows/git-artifacts.yml
@@ -48,6 +48,58 @@ jobs:
       mingw_package_prefix: ${{steps.configure-environment.outputs.MINGW_PACKAGE_PREFIX}}
       sdk_repo_arch: ${{steps.configure-environment.outputs.SDK_REPO_ARCH}}
     steps:
+      - name: clone git-for-windows-automation
+        run: git clone --single-branch -b $GITHUB_REF_NAME https://github.com/git-for-windows/git-for-windows-automation
+      - name: Construct bundle-artifacts from existing tag
+        if: env.EXISTING_GIT_TAG != ''
+        run: |
+          die () {
+            echo "$*" >&2
+            exit 1
+          }
+
+          test -z "$TAG_GIT_WORKFLOW_RUN_ID" ||
+          die 'existing_git_tag cannot be used with tag_git_workflow_run_id!'
+
+          test -n "$BUILD_EXTRA_REV_FOR_EXISTING_GIT_TAG" ||
+          die 'existing_git_tag needs build_extra_rev_for_existing_git_tag!'
+
+          set -o pipefail &&
+
+          mkdir -p bundle-artifacts &&
+          echo "$EXISTING_GIT_TAG" >bundle-artifacts/next_version &&
+          echo "$EXISTING_GIT_TAG" |
+          sed -n '/^v[0-9]\+\.[0-9]\+\.[0-9]\+\.windows\.[0-9]\+$/{s/^v//;s/\.windows\.1//;s/\.windows\.\(.*\)/(\1)/;p}' \
+            >bundle-artifacts/display_version &&
+          sed 's/(\(.*\))$/.\1/' <bundle-artifacts/display_version >bundle-artifacts/ver
+      - name: Get bundle-artifacts download URL
+        uses: actions/github-script@v6
+        if: env.TAG_GIT_WORKFLOW_RUN_ID != ''
+        id: get-bundle-artifacts-url
+        with:
+          script: |
+            if (process.env.EXISTING_GIT_TAG || process.env.BUILD_EXTRA_REV_FOR_EXISTING_GIT_TAG) {
+              throw new Error('tag_git_workflow_run_id cannot be used with existing_git_tag or build_extra_rev_for_existing_git_tag!')
+            }
+            const getDownloadURL = require('./git-for-windows-automation/get-workflow-run-artifact')
+            const workflowRunId = process.env.TAG_GIT_WORKFLOW_RUN_ID
+            core.info('Getting download URL for bundle-artifacts...')
+            const downloadURL = await getDownloadURL(github, context.repo.owner, context.repo.repo, workflowRunId, 'bundle-artifacts')
+
+            core.info(`Successfully got download URL. It expires after 1 minute: ${downloadURL}`)
+            core.setOutput('download-url', downloadURL)
+      - name: Download bundle-artifacts zip
+        if: env.TAG_GIT_WORKFLOW_RUN_ID != ''
+        run: |
+          mkdir bundle-artifacts
+          curl -o bundle-artifacts.zip "${{steps.get-bundle-artifacts-url.outputs.download-url}}"
+          unzip bundle-artifacts.zip -d bundle-artifacts
+          echo "GIT_VERSION=$(cat bundle-artifacts/next_version)" >> $GITHUB_ENV
+      - name: Re-publish bundle-artifacts so the next job can easily use it
+        uses: actions/upload-artifact@v3
+        with:
+          name: bundle-artifacts
+          path: bundle-artifacts
       - name: Configure environment
         id: configure-environment
         run: |
@@ -99,8 +151,6 @@ jobs:
         with:
           flavor: build-installers
           architecture: ${{env.architecture}}
-      - name: clone git-for-windows-automation
-        run: git clone --single-branch -b $GITHUB_REF_NAME https://github.com/git-for-windows/git-for-windows-automation
       - name: Create artifact build matrix
         uses: actions/github-script@v6
         id: artifact-build-matrix
@@ -115,56 +165,6 @@ jobs:
             } catch (e) {
               core.setFailed(e.message)
             }
-      - name: Construct bundle-artifacts from existing tag
-        if: env.EXISTING_GIT_TAG != ''
-        run: |
-          die () {
-            echo "$*" >&2
-            exit 1
-          }
-
-          test -z "$TAG_GIT_WORKFLOW_RUN_ID" ||
-          die 'existing_git_tag cannot be used with tag_git_workflow_run_id!'
-
-          test -n "$BUILD_EXTRA_REV_FOR_EXISTING_GIT_TAG" ||
-          die 'existing_git_tag needs build_extra_rev_for_existing_git_tag!'
-
-          set -o pipefail &&
-
-          mkdir -p bundle-artifacts &&
-          echo "$EXISTING_GIT_TAG" >bundle-artifacts/next_version &&
-          echo "$EXISTING_GIT_TAG" |
-          sed -n '/^v[0-9]\+\.[0-9]\+\.[0-9]\+\.windows\.[0-9]\+$/{s/^v//;s/\.windows\.1//;s/\.windows\.\(.*\)/(\1)/;p}' \
-            >bundle-artifacts/display_version &&
-          sed 's/(\(.*\))$/.\1/' <bundle-artifacts/display_version >bundle-artifacts/ver
-      - name: Get bundle-artifacts download URL
-        uses: actions/github-script@v6
-        if: env.TAG_GIT_WORKFLOW_RUN_ID != ''
-        id: get-bundle-artifacts-url
-        with:
-          script: |
-            if (process.env.EXISTING_GIT_TAG || process.env.BUILD_EXTRA_REV_FOR_EXISTING_GIT_TAG) {
-              throw new Error('tag_git_workflow_run_id cannot be used with existing_git_tag or build_extra_rev_for_existing_git_tag!')
-            }
-            const getDownloadURL = require('./git-for-windows-automation/get-workflow-run-artifact')
-            const workflowRunId = process.env.TAG_GIT_WORKFLOW_RUN_ID
-            core.info('Getting download URL for bundle-artifacts...')
-            const downloadURL = await getDownloadURL(github, context.repo.owner, context.repo.repo, workflowRunId, 'bundle-artifacts')
-
-            core.info(`Successfully got download URL. It expires after 1 minute: ${downloadURL}`)
-            core.setOutput('download-url', downloadURL)
-      - name: Download bundle-artifacts zip
-        if: env.TAG_GIT_WORKFLOW_RUN_ID != ''
-        run: |
-          mkdir bundle-artifacts
-          curl -o bundle-artifacts.zip "${{steps.get-bundle-artifacts-url.outputs.download-url}}"
-          unzip bundle-artifacts.zip -d bundle-artifacts
-          echo "GIT_VERSION=$(cat bundle-artifacts/next_version)" >> $GITHUB_ENV
-      - name: Re-publish bundle-artifacts so the next job can easily use it
-        uses: actions/upload-artifact@v3
-        with:
-          name: bundle-artifacts
-          path: bundle-artifacts
       - name: Clone and update build-extra
         run: |
           d=/usr/src/build-extra &&
