publish-embargoed-nuget-packages: mirror a Check Run into the originating PR
This follows the common pattern of mirroring a Check Run into the
repository where the package originated from.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/.github/workflows/publish-embargoed-nuget-packages.yml b/.github/workflows/publish-embargoed-nuget-packages.yml
--- a/.github/workflows/publish-embargoed-nuget-packages.yml
+++ b/.github/workflows/publish-embargoed-nuget-packages.yml
@@ -20,9 +20,58 @@ jobs:
     runs-on: windows-latest
     steps:
       - name: sanity check
-        if: github.repository_visibility != 'private' || github.repository.fork == true
-        run: echo "This action is meant to be run in an embargoed org" >&2; exit 1
+        run: |
+          case '${{ github.repository_visibility }},${{ github.repository.fork }}'
+          private,false) ;; # okay
+          *)
+            echo "::error::This action is meant to be run in an embargoed org" >&2
+            exit 1
+            ;;
+          esac
+
+          s="$(echo "$GITHUB_RELEASE_URL" |
+            sed -n 's|https://github.com/$OWNER/\([^/]+)/releases/tag/\([^/]+)$|REPOSITORY=\1\nTAG=\2|p')"
+          test -n "$s" || {
+            echo "::error:: Cannot parse URL '$GITHUB_RELEASE_URL'" >&2
+            exit 1
+          }
+          echo "$s" >>$GITHUB_ENV
       - uses: actions/checkout@v4
+      - name: obtain info for check-run
+        id: token
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const { getAccessTokenForRepo } = require('./github-release.js')
+            const token = await getAccessTokenForRepo(
+              console,
+              core.setSecret,
+              ${{ secrets.GH_APP_ID }},
+              ${{ toJSON(secrets.GH_APP_PRIVATE_KEY) }},
+              process.env.OWNER,
+              process.env.REPOSITORY
+            )
+            const githubApiRequest = require('./github-api-request')
+            const refData = await githubApiRequest(
+              console,
+              token,
+              'GET',
+              `/repos/${process.env.OWNER}/${process.env.REPOSITORY}/git/ref/tags/${process.env.TAG}`
+            )
+            core.exportVariable('REV', refData.object.sha)
+      - name: Mirror Check Run to ${{ env.OWNER }}/${{ env.REPOSITORY }}
+        uses: ./.github/actions/check-run-action
+        with:
+          app-id: ${{ secrets.GH_APP_ID }}
+          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
+          owner: ${{ env.OWNER }}
+          repo: ${{ env.REPOSITORY }}
+          rev: ${{ env.REV }}
+          check-run-name: "publish-embargoed-nuget-packages"
+          title: "Publish ${{ env.TAG }} to the public Git for Windows NuGet feed"
+          summary: "This deploys the previously-embargoed embargoed Git for Windows ${{ env.TAG }} to the NuGet feed."
+          text: "For details, see [this run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}})."
+          details-url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}"
       - name: download package files
         uses: actions/github-script@v7
         with:
@@ -54,3 +103,11 @@ jobs:
               -Timeout 3000 \
               "$nupkg" || exit 1
           done
+      - name: update check-run
+        if: always()
+        uses: ./.github/actions/check-run-action
+        with:
+          app-id: ${{ secrets.GH_APP_ID }}
+          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
+          append-text: "${{ github.action_status == 'success' && 'Done!' || format('Completed: {0}', github.action_status) }}."
+          conclusion: ${{ github.action_status }}
